### ISSUE TITLE
 gsas2full-5773-MacOSX-x86_64.sh errors

### ISSUE THREAD

**Issue by creuzige** [AdvancedPhotonSource/GSAS-II#16]
I tried to install GSAS-II via the self-installer downloads at https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/releases/tag/v1.0.1, but the install failed (see commands below).  I think the installer is looking for an exe file that I likely don't have (MacOS 14.4, Intel Core i7)

PS - The installer implies the version is 4446, but the download page implies 5773.  Which is correct?

PSS - Do you want installer questions here, or in build tools (https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/).  The new webpage guidance only directs here (https://advancedphotonsource.github.io/GSAS-II-tutorials/bug.html)

```
cd Downloads/
./gsas2full-4446-MacOSX-x86_64.sh 

Welcome to gsas2full 4446

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue

Do you accept the license terms? [yes|no]
[no] >>> yes

gsas2full will now be installed into this location:
/Users/**********/gsas2full

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/Users/**********/gsas2full] >>> /Users/**********/gsas2full-5773  
PREFIX=/Users/**********/gsas2full-5773
Unpacking payload ...
/Users/**********/gsas2full-5773/conda.exe: line 1: =============================================: command not found
/Users/**********/gsas2full-5773/conda.exe: line 2: syntax error near unexpected token `c'
/Users/**********/gsas2full-5773/conda.exe: line 2: ` Copyright (c) 2016, Continuum Analytics, Inc.'
ERROR: could not extract tar starting at offset 000000000000015246+9490254+2


````

**Comment by briantoby** [comment]
On Apr 17, 2024, at 10:03 AM, Adam Creuziger - NIST ***@***.***> wrote:


This Message Is From an External Sender
This message came from outside your organization.


I tried to install GSAS-II via the self-installer downloads at https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/releases/tag/v1.0.1<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/releases/tag/v1.0.1__;!!G_uCfscf7eWS!YL3rnbcQIqlxr22bDODaydj6XyZ0pZm-b69u05PYxuccgYmvKVds34dKFf-Yzd_omu2XquDk4nSOFYQHHs8twk7dUNE$>, but the install failed (see commands below). I think the installer is looking for an exe file that I likely don't have (MacOS 14.4, Intel Core i7)

PS - The installer implies the version is 4446, but the download page implies 5773. Which is correct?

PSS - Do you want installer questions here, or in build tools (https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/__;!!G_uCfscf7eWS!YL3rnbcQIqlxr22bDODaydj6XyZ0pZm-b69u05PYxuccgYmvKVds34dKFf-Yzd_omu2XquDk4nSOFYQHHs8tJK3Iue4$>). The new webpage guidance only directs here (https://advancedphotonsource.github.io/GSAS-II-tutorials/bug.html<https://urldefense.us/v3/__https://advancedphotonsource.github.io/GSAS-II-tutorials/bug.html__;!!G_uCfscf7eWS!YL3rnbcQIqlxr22bDODaydj6XyZ0pZm-b69u05PYxuccgYmvKVds34dKFf-Yzd_omu2XquDk4nSOFYQHHs8tAtYcVRg$>)

cd Downloads/
./gsas2full-4446-MacOSX-x86_64.sh

Welcome to gsas2full 4446

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue

Do you accept the license terms? [yes|no]
[no] >>> yes

gsas2full will now be installed into this location:
/Users/**********/gsas2full

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/Users/**********/gsas2full] >>> /Users/**********/gsas2full-5773
PREFIX=/Users/**********/gsas2full-5773
Unpacking payload ...
/Users/**********/gsas2full-5773/conda.exe: line 1: =============================================: command not found
/Users/**********/gsas2full-5773/conda.exe: line 2: syntax error near unexpected token `c'
/Users/**********/gsas2full-5773/conda.exe: line 2: ` Copyright (c) 2016, Continuum Analytics, Inc.'
ERROR: could not extract tar starting at offset 000000000000015246+9490254+2

**Comment by creuzige** [comment]
Looks like I was running an older file.  It looks like the issue was that the 5773 version shows up as 644 permissions, and then is not executable like the 4446 version.  So when I tried ./<gsas>  it only found the 4446 version.  After chmod to change the permissions it was fine.  Not sure if that was an issue with the download or something on the file...

**Comment by briantoby** [comment]
All issues should go here. I turned them off on the two auxiliary repos to help reduce confusion. 

The instructions say to use "bash file.sh" rather than "./file.sh" to avoid the permissions issue (as well as where people are set to use a different shell than bash).

**Comment by creuzige** [comment]
Good point on the bash command vs. ./<gsas> definitely a [PEBKAC error](https://en.wikipedia.org/wiki/User_error).  I do recall a note about the different command structure, but was confused in figuring out if I should use the current shell or a specific one.  

When I checked I couldn't find the note about using "bash file.sh" rather than "./file.sh" (but again recall seeing it somewhere)

I checked the following links:

https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/releases/tag/v1.0.1
https://advancedphotonsource.github.io/GSAS-II-tutorials/install.html
https://advancedphotonsource.github.io/GSAS-II-tutorials/install-g2f-mac.html
