### ISSUE TITLE
EDX instrument parameter file does not load properly

### ISSUE THREAD

**Issue by adrienneri** [AdvancedPhotonSource/GSAS-II#51]
Dear GSAS-II team,

I am using GSAS-II to analyze my EDX data, and that I noticed that when I load the ".instprm" file, some of the coefficients do not load properly. Surprisingly, the XE, YE and ZE correspond to the values in the default X-ray EDS ".instprm" file. Would there be a way to fix this issue?
I am using the most up to date version of GSAS-II. Attached is the ".instprm" file with the XE, YE and ZE coefficients (I had to compress it so that GitHub would take it).
[BT531_D2.instprm.zip](https://github.com/user-attachments/files/16424563/BT531_D2.instprm.zip)

All the best,
Adrien Néri

**Comment by briantoby** [comment]
@vondreele This might be best for you to look at. If not, I will ask for a sample data file.

**Comment by briantoby** [comment]
Bob is also requesting a sample data file to use in testing

**Comment by adrienneri** [comment]
Thank you for the replies !

Attached is sample file data: ED-XRD pattern of alumina at around 6-8 GPa and 300 K. Based on our calibration, the 2-theta angle is 3.9913 °.
[BT531_005_083bar_000W_BR.gsas1.zip](https://github.com/user-attachments/files/16441599/BT531_005_083bar_000W_BR.gsas1.zip)

Cheers,
Adrien

**Comment by briantoby** [comment]
Is this addressed?

**Comment by vondreele** [comment]
Thanks for the reminder. I have the data. I'll Look at it tomorrow.
________________________________

**Comment by briantoby** [comment]
presuming that Bob's changes take care of this. If not, please reopen with comments as to what more is needed.

**Comment by Te-rex83** [comment]
GSAS v7493c2, 23 Nov 2024, Full version, Windows 11

This problem still needs to be addressed because a lot of new ED-XRD data is continuously produced at the High-energy Wiggler beamline station P61B. 

- The last properly working version of GSASII was v5624, before the implementation of additional Lorentzian fitting. 
- In the latest version (see above), the instrument pararameter file seems to have different formatting than before:

`#GSAS-II instrument parameter file; do not add/delete items!
Type:PXE
2-theta:4.99516
A:0.0
B:0.00039585
C:0.0
X:2.038871e-05
Y:-0.0022679
Z:0.0124504
Bank:1.0
Diff-type:Debye-Scherrer
Gonio. radius:200.0`

- The questions are: 
1) Why does this format keep changing? 
2) Why do these entries not match the entries in the GUI? It seems XE, YE, and ZE are missing. And there is an additional entry WE. What are these? 
3) Why can these not be refined, and why are they not set to zero by default?
4) Are X,Y and Z the 'new' instrument parameters for the Ge-detector? What corrections do they make? It seems they can easily be set to zero with negligible effect on the LeBail full profile fitting.
5) The lines Diff-type: Debye-Scherrer, and Gonio. radius:200.0 should be ignored for ED-XRD patterns.

**Comment by Te-rex83** [comment]
Also, while still on-topic, it would be great if the B parameter for the peak shape in a refinement can be specific to the added phases, rather than using it as a global parameter.

**Comment by vondreele** [comment]
Hi,
A few points:
The parameters XE, YE, ZE & WE are the MCA calibration parameters for channel number to energy; they are found in the data header. They are only shown in the Instrument Parameters for information. They are currently not refinable - they are (in my understanding) established by the MCA manufacturer; they only got used when the EDX data was imported to convert channel no. to energy. After that it doesn't matter what their values are. The 2-theta value is refinable by using a standard with known lattice parameter. A, B, C are Gaussian instrument broadening terms & X, Y,  Z are Lorentzian instrument broadening terms (hard to know a situation where they could be non-zero). Sample broadening in GSAS-II is always handled in the Data tab for the phase; those are phase/histogram specific & have possibly complex forms. The sample broadening is almost invariably Lorentzian so trying to use B for that isn't appropriate anyway. Given the low resolution of most EDX patterns, finding sample broadening will be difficult unless the broadening is pretty extreme. NB: most sample broadening is due to microstrain not crystallite size (except for nanomaterials - submicron in size). As for gonio. radius - it could be of use for determining a sample displacement even for EDX patterns - possible future development.
As for the instprm file - the order doesn't matter & could change with python version as it is a rendering of a dictionary.
Best,
Bob
________________________________

**Comment by Te-rex83** [comment]
Dear Bob,

Thank you for the detailed explanation. I was concerned the instrument file was not loading correctly in the new GSAS versions, but that is not the case. Then, in my understanding, this issue can stay solved. 

-Robert Farla
