### ISSUE TITLE
The Bruker RAW format file can not be read

### ISSUE THREAD

**Issue by Putin0922** [AdvancedPhotonSource/GSAS-II#63]
The Bruker RAW format file cannot be read by the GSAS 2 (latest version, installed on Windows 11 by GSAS2FULL installer), the relavant error messages are as follows:

The Bruker RAW ver. 1 reader was not able to read file ~\XX.raw

Error message(s):

Bruker RAW ver. 1 read error:
  Unhandled read exception:
  Traceback info:
Traceback (most recent call last):
  File "D:\GSAS2\GSAS-II\GSASII\GSASIIdataGUI.py", line 1115, in OnImportGeneric
    flag = rd.Reader(filename,self,buffer=rdbuffer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GSAS2\GSAS-II\GSASII\imports\G2pwd_BrukerRAW.py", line 76, in Reader
    raise Exception    #for now
    ^^^^^^^^^^^^^^^
Exception

Are there any solution for this issue?

Appreciate for your help!

**Comment by briantoby** [comment]
Hi,

   Looking at the GSAS-II code, the problem here is that you have a Bruker version 1 data file and we have not written code to read that form. We can read versions 2, 3 & 4 but not 1. Is there any chance you can upgrade the diffractometer software? If not, perhaps there is some file conversion software that you can obtain that will read that file and convert it to something that GSAS-II does support?

   If you would like to supply a sample dataset (zip it and attach it to the GitHub issue) and the file it is fairly straightforward to interpret, we might be able to add support for Version 1 to the importer, but I don’t promise that will happen. OTOH I will offer to help if you want to try to write some Python code that we could eventually add.

Brian

From: Putin0922 ***@***.***>
Date: Tuesday, September 3, 2024 at 7:29 AM
To: AdvancedPhotonSource/GSAS-II ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AdvancedPhotonSource/GSAS-II] The Bruker RAW format file can not be read (Issue #63)
The Bruker RAW format file cannot be read by the GSAS 2 (latest version, installed on Windows 11 by GSAS2FULL installer), the relavant error messages are as follows: The Bruker RAW ver. 1 reader was not able to read file ~\XX. raw Error message(s): 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

The Bruker RAW format file cannot be read by the GSAS 2 (latest version, installed on Windows 11 by GSAS2FULL installer), the relavant error messages are as follows:

The Bruker RAW ver. 1 reader was not able to read file ~\XX.raw

Error message(s):

Bruker RAW ver. 1 read error:
Unhandled read exception:
Traceback info:
Traceback (most recent call last):
File "D:\GSAS2\GSAS-II\GSASII\GSASIIdataGUI.py", line 1115, in OnImportGeneric
flag = rd.Reader(filename,self,buffer=rdbuffer,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\GSAS2\GSAS-II\GSASII\imports\G2pwd_BrukerRAW.py", line 76, in Reader
raise Exception #for now
^^^^^^^^^^^^^^^
Exception

Are there any solution for this issue?

Appreciate for your help!

**Comment by Putin0922** [comment]
Appreciate for you help!
After changing the .raw ver. 1 format into the .raw ver. 2 format, the file can be imported into the GSAS2.
However, a new problem has arisen, the .raw ver. 2 XRD pattern drawn by the GSAS2 plot is shown as the picture below:
![屏幕截图 2024-09-05 114741](https://github.com/user-attachments/assets/559d2565-d618-4ac4-977a-988c69ee6563)
While the same .raw ver. 2 opened by Jade 6 is shown as:
![屏幕截图 2024-09-05 114827](https://github.com/user-attachments/assets/3bb78cfe-ac47-4297-802a-7c09bd42ad87)
It seems the XRD pattern is not properly imported into GSAS2. And there is no any error information given by the software. Are there any solution for this problem? I will be grateful for you to address this issue!

**Comment by briantoby** [comment]
Yes, clearly there is something wrong with our importer. It got the right values for the x-axis, but not the intensities. Could you supply a file that we can use for debugging? A plot from Jade of that data would be helpful.

**Comment by Putin0922** [comment]
For sure I'd would be pleasure to provide the relevant file to you for debugging. Could you tell me which file(s) you need specifically? And by the way could you provide a personal contact information (e.g. a personal email) for me to ensure the relevant files are sent to the right place and right person?

**Comment by briantoby** [comment]
Please email ***@***.*** (Toby at ANL dot gov). One or two samples datasets of anything with peaks in the raw2 format. Plots of what the data should look like helps too.

Brian

Typos are my fault, but assisted by a tiny screen and so-called AI.
________________________________

**Comment by Putin0922** [comment]
The email has been sent, please check your email box

**Comment by briantoby** [comment]
The RAW2 read issue is now fixed in 4514980b. Nothing has been done w/r to the original unnumbered ("RAW ") format, but the error message was updated to be a bit more clear.
