### ISSUE TITLE
GSAS II not working with ISIS SXD data

### ISSUE THREAD

**Issue by mjg1-ui** [AdvancedPhotonSource/GSAS-II#74]
Dear all,

I'm trying to refine ISIS SXD data using the latest version of GSAS II on Windows 11. First, I 'Import' -> 'Structure Factor' -> 'From neutron TOF JANA2000 F2 file'. This seems to work. Then I add a phase and add the atoms  'Edit atoms' -> 'Append atom'.

Then I was adding the imported histograms assuming this would associate them with the phase.

Trying to do 'Calculate' -> 'Refine' gives a 'KeyError': 'Flack'.

How can I get this to work? Was there a GSAS II tutorial for the ISIS SXD at some point?

Also, the site 'Na2' and 'Fe2' should be constrained to have identical (x,y,z), ADP's and sum of occupancies set to 1.0.

Strange enough, GSAS saved the .gpx file and associated files in a completely different folder. From this different folder, I was trying
to import the crystal structure from a cif file from a database. GSAS did not understand the space group. So did it by hand.
[Na1.1FeO2_SmallXtal_20K_JANASXD_sb.zip](https://github.com/user-attachments/files/17307016/Na1.1FeO2_SmallXtal_20K_JANASXD_sb.zip)

Any help would be much appreciated.

Many thanks and best wishes,

Matthias

**Comment by briantoby** [comment]
I'll try to get to this soon. There is definitely a bug here that needs to be addressed, but probably a few other things that we should discuss. Also, I'd like to see a copy of that CIF that you could not read. 

Issues noted: 
- Flack bug (again, dammit)
- shared site constraints (question?)
- save in wrong folder
- space group unrecognized (common) but should manage to import everything else

Note: review how version info is saved in .gpx

**Comment by mjg1-ui** [comment]
Hi Toby,

many thanks for your reply. Yes, the issue with the constraints is a question how to do this. I am sure it can be done.

Please, find attached the CIF file from a database.

Many thanks and best wishes,
[icsd_116508_cifbib.zip](https://github.com/user-attachments/files/17324589/icsd_116508_cifbib.zip)


Matthias

**Comment by briantoby** [comment]
Matthias -- sorry I have been so slow in getting to this. I seem to have gotten myself buried in a series of "this will be quick" fixes, with my attention to this keep getting bumped back. 

The Flack parameter error is one that I don't fully understand. The code should set a default value for that when the phase is linked to the single crystal dataset(s) and I don't see why that is not happening, but it is easy enough to add a "fix" downstream so that the default value (0) is set before it is first used. If you update, you should be able to perform the refinement. 

The CIF problem was a bit more tricky. The importer should read in a CIF without a space group name specified, so that one gets the atom & cell info, but the default the space group is then set to P1. That got broken when Bob added the capability to handle BNS space groups, but that is now fixed. Your CIF did have a space group specified -- as a space group number (not an ideal choice by the database software IMO). I also added the ability to handle that, so now your CIF will read just fine. 

The constraint for shared sites is easy to set up. Use this:

<img width="674" alt="image" src="https://github.com/user-attachments/assets/e560e3f2-ea3b-4005-b7de-8244324a8b59">

I think the rest will be obvious. Note that this will set up Uiso equivalences if the atoms are isotropic or Uij equivalences if the atoms are anisotropic. You can also set up the individual constraint equations/equivalences yourself if you want (or later if you switch from iso to aniso). 

I'll close this issue now, but get in touch if you have more questions or reopen if there are still problems.
