### ISSUE TITLE
Complying with Anaconda terms of service

### ISSUE THREAD

**Issue by jamesrhester** [AdvancedPhotonSource/GSAS-II#96]
Our organisation is worried that we might be violating the Anaconda terms of service by using Anaconda or miniconda to access the official anaconda repositories during/after a GSAS-II install on Windows. As far as I can tell from the [build scripts](https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/blob/main/install/windows_notes.txt) `(this is old -- see below [BHT])`, as long as the `conda` commands that were run to create the installer come from something like conda-forge there is no issue. Can someone confirm that this is the case? I don't have a convenient Windows computer to investigate the installer.

**Comment by briantoby** [comment]
We are no longer using any Python/packages downloaded directly from Anaconda.com or from any of their conda channels. Not due to any desire to avoid them, but because they stopped offering wxPython. Perhaps this was good fortune in retrospect, if Anaconda is clamping down on use of their dists. For the gsas2full self-installer, we use only miniforge and packages from the conda-forge server. For people who choose to install within a conda environment, they use the gsas2pkg conda package, which lives in the briantoby channel on anaconda.org. 

I am not able to speak to any legal implications from using the the conda program and the conda-build and conda-construct tools. They originated with Anaconda, but I was of the understanding that they are available for open use. Certainly there is whole infrastructure on GitHub built around them. Likewise, I don't think use of Anaconda.org for hosting Python packages carries any legal burdens, but I am open to being educated further on any of this. 

GSAS-II can be used in a completely Anaconda-free way, but one needs to install Python 3.11 & numpy 1.26 and all the other needed packages via pip and then download GSAS-II from GitHub. There is a goal of making GSAS-II available via PyPi (@tacaswell), which is not active right now, but when that happens this will become much simpler. 

N.B. the build script referenced above is old. Scripts for building GSAS2FULL and GSAS2PKG are all here: https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/tree/main/.github

**Comment by jamesrhester** [comment]
Thanks for the detailed response. I think it confirms that there is no need to purchase a subscription if using the gsas2full self-installer.

**Comment by briantoby** [comment]
The intent is that GSAS-II distributions should not require use of any proprietary tools, but I cannot claim I understand the legal side of all this to insist that is true.
